[workspace]
resolver = "2"
members = ["apps/http-api"]

[workspace.dependencies]
# --- Async & Runtime ---
async-trait = "0.1.88"
tokio = { version = "1.47.1", features = ["full"] }

# --- Web Framework & HTTP ---
axum = { version = "0.8.4", features = ["macros"] }
tower-http = { version = "0.6.6", features = ["trace", "cors"] }

# --- Tracing & Logging ---
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# --- Utilities ---
dotenvy = "0.15"
